name: player
version: @version@
main: xyz.tehbrian.mcmidi.player.PlayerPlugin
api-version: 1.16
authors: [ TehBrian ]
description: Plays note events sent out by mcmidi server.
website: https://github.com/mcmidi-uwu/player
depend: [ server ]
