name: mcmidi-player
description: Plays mcmidi note requests.
authors: [ TehBrian ]
website: https://github.com/mcmidi-uwu/player

depend: [ mcmidi-server ]

version: ${version}
main: xyz.tehbrian.mcmidi.player.PlayerPlugin
api-version: 1.18
